### ISSUE TITLE
Error: Start tag expected, '<' not found

### ISSUE THREAD

**Issue by tmfksoft** [clux/wolfram-alpha#5]
I've recently wrote a utility bot that repeatedly crashes at random when people run something through wolfram alpha.

I'm getting the following error when that happens:

`/home/thomas/paper_bot/node_modules/libxmljs/lib/document.js:168
    return bindings.fromXml(string, options || {});
                    ^

Error: Start tag expected, '<' not found

    at Error (native)
    at Object.module.exports.fromXml (/home/thomas/paper_bot/node_modules/libxmljs/lib/document.js:168:21)
    at Request._callback (/home/thomas/paper_bot/node_modules/wolfram-alpha/wolfram.js:58:19)
    at Request.self.callback (/home/thomas/paper_bot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/thomas/paper_bot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/thomas/paper_bot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

Any ideas on what is wrong?

**Comment by clux** [comment]
Hey, thanks for the report. I haven't used this module in a while, CI does appear to fail now: https://travis-ci.org/clux/wolfram-alpha/jobs/132341822 - so it's likely some problem in here. Maybe schemas from wolfram alpha have changed or something :/

**Comment by tmfksoft** [comment]
No problem :)
I do appear to get slightly different errors each time, generaly related to parsing.
Even stuff such as getting a null result and no error.

**Comment by clux** [comment]
Whoops auto-close. At any rate, I've bumped all the dependencies and fixed up tests. If you upgrade to wolfram-alpha@0.6.0 you may find it works, if not please report back :)

I did change the main interface to be promise based in the process though, if you don't want to deal with that right now, you can change your calls to `client.query` to `client.queryCb`.

**Comment by tmfksoft** [comment]
Many thanks!
I've updated to latest and it appears to be running fine.
I'll update this issue or create a new one if I have any issues :)
