### ISSUE TITLE
Can't install it with npm

### ISSUE THREAD

**Issue by ssantoshp** [clux/wolfram-alpha#8]
Hi I have a problem when I try to install this package.

I did:

```npm i wolfram-alpha```

and it gave me:

```py
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=C:\\Users\\Geetha\\appli-ionic\\samsan\\node_modules\\wolfram-alpha\\node_modules\\libxmljs\\build\\Release\\xmljs.node" "--module_name=xmljs" "--module_path=C:\\Users\\Geetha\\appli-ionic\\samsan\\node_modules\\wolfram-alpha\\node_modules\\libxmljs\\build\\Release" "--napi_version=7" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --loglevel=http --module=C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs\build\Release --napi_version=7 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Geetha\\appli-ionic\\samsan\\node_modules\\wolfram-alpha\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --loglevel=http --module=C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\Geetha\appli-ionic\samsan\node_modules\wolfram-alpha\node_modules\libxmljs\build\Release --napi_version=7 --node_abi_napi=napi' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Geetha\appli-ionic\samsan\package.json'
npm WARN samsan No description
npm WARN samsan No repository field.
npm WARN samsan No README data
npm WARN samsan No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Geetha\AppData\Roaming\npm-cache\_logs\2021-08-25T13_43_08_751Z-debug.log
```

How can I solve that please?

**Comment by clux** [comment]
Sounds like you either don't have libxml installed on windows, or that libxmljs's install script doesn't work on windows. Don't have windows so not really able to help here.
